name: Postman Test and Allure Report

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install newman and newman-reporter-allure
        run: |
          npm install -g newman newman-reporter-allure
          echo "Newman and newman-reporter-allure installed."

      - name: Run Postman tests
        run: |
           newman run Open_Banking_QA.postman_collection.json --reporters cli,allure
           echo "Postman tests run."

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
    
      - name: Allure report action
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Wait for Allure report to be generated
        run: sleep 10

      # - name: Find latest folder and update Allure Report Title
      #   run: |
      #     latest_folder=$(find allure-report -type d -name '[0-9]*' | sort -n | tail -n 1)
      #     echo "Latest Folder: $latest_folder"
      #     sed -i 's/<title>Allure Report<\/title>/<title>[Open Banking] - API Quality Readiness<\/title>/' "$latest_folder/index.html"

      - name: Deploy report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

      - name: Update Allure Report Widget Title
        run: |
          # Find the latest folder with numerical values in the gh-pages branch
          latest_folder=$(find gh-pages -mindepth 1 -maxdepth 1 -type d -name '[0-9]*' | sort -n | tail -n 1)
          
          echo "Latest Folder: $latest_folder"
          
          # Check if index.html exists in the latest folder
          index_html_path="$latest_folder/index.html"
          echo "Index HTML Path: $index_html_path"
          
          if [[ -e "$index_html_path" ]]; then
            # Debug output to check the content before and after the sed command
            cat "$index_html_path"  # Print content before
            
            # Use sed to update the content within the <h2> element
            sed -i 's/<h2 class="widget__title">.*<\/h2>/<h2 class="widget__title">[New Content]<\/h2>/' "$index_html_path"
            
            cat "$index_html_path"  # Print content after
          else
            echo "Error: index.html not found in the latest folder."
          fi
