name: Postman Test and Allure Report

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Postman tests
      run: |
        docker run -t -v "$(pwd):/etc/newman" postman/newman run /etc/newman/Open_Banking_QA.postman_collection.json --reporters cli,junit --reporter-junit-export /etc/newman/test-results.xml

    - name: Download and Install Allure
      run: |
        sudo apt-get install -y allure

    # - name: Find Allure binary
    #   run: |
    #     ls -l /usr/bin/allure

    - name: Create Allure report directory
      run: mkdir -p ./allure-report

    - name: Generate Allure report
      run: |
        /path/to/allure generate /etc/newman/allure-results --clean -o ./allure-report

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
