name: Postman Test and Allure Report

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install newman and newman-reporter-allure
      run: |
        npm install -g newman newman-reporter-allure
        echo "Newman and newman-reporter-allure installed."

    - name: Run Postman tests
      run: |
        docker run -t -v "$(pwd):/etc/newman" postman/newman run /etc/newman/Open_Banking_QA.postman_collection.json --reporters cli,allure
        echo "Postman tests run."

    - name: Get Allure history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
          ref: gh-pages
          path: gh-pages
      run: |
        echo "Allure history retrieved."

    - name: Allure report action
      uses: ./path/to/run-allure-report.sh

    - name: Deploy Allure report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
      run: |
        echo "Allure report deployed to GitHub Pages."
